name: Check Dependencies

on:
  pull_request:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: kubernetes-sigs/release-actions/setup-zeitgeist@8af7b2a5596dff526de9db59b2c4b8457e9f52a1 # v0.4.0

      - run: zeitgeist validate --config ./dependencies.yaml
