name: Check Dependencies

on:
  pull_request:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: kubernetes-sigs/release-actions/setup-zeitgeist@2f8b9ec22aedc9ce15039b6c7716aa6c2907df1c # v0.2.0

      - run: zeitgeist validate --config ./dependencies.yaml
