name: Check Dependencies

on:
  pull_request:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: cpanato/setup-zeitgeist@3e861b7af3b3b4096b0b4837b612bf0665bdb308 # v0.0.2

      - run: zeitgeist validate --config ./dependencies.yaml
