name: Check Dependencies

on:
  pull_request:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: kubernetes-sigs/release-actions/setup-zeitgeist@a30d93cf2aa029e1e4c8a6c79f766aebf429fddb # v0.3.1

      - run: zeitgeist validate --config ./dependencies.yaml
