name: Check Dependencies

on:
  pull_request:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: cpanato/setup-zeitgeist@3e861b7af3b3b4096b0b4837b612bf0665bdb308 # v0.0.2

      - run: zeitgeist validate --config ./dependencies.yaml
