name: Check Dependencies

on:
  pull_request:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: kubernetes-sigs/release-actions/setup-zeitgeist@a69972745f85aab4ba5d6c681e2a0e7f73eaff2b # v0.3.0

      - run: zeitgeist validate --config ./dependencies.yaml
